// frontend/inchain-react/src/routes/RoleGuard.tsx
import type { ReactNode } from "react";
import { Navigate, Outlet } from "react-router";
import type { UserRole } from "../features/auth/authTypes";
import { useAuth } from "../features/auth/useAuth";
import { paths } from "./paths";

type RoleGuardProps = {
  allowedRoles: UserRole[];
  children?: ReactNode;
};

function RoleGuard({ allowedRoles, children }: RoleGuardProps) {
  const { roles } = useAuth();
  const hasAllowedRole = roles.some((role) => allowedRoles.includes(role));

  if (!hasAllowedRole) {
    return <Navigate to={paths.unauthorized} replace />;
  }

  return children ?? <Outlet />;
}

export default RoleGuard;

// frontend/inchain-angular/src/app/shared/guards/role.guard.ts
import { inject } from '@angular/core';
import { CanActivateFn, Router } from '@angular/router';
import { AuthService } from '@/features/auth/auth.service';
import type { UserRole } from '@/shared/models/auth.types';

export function roleGuard(allowedRoles: UserRole[]): CanActivateFn {
  return () => {
    const authService = inject(AuthService);
    const router = inject(Router);

    const userRoles = authService.roles();
    const hasAllowedRole = userRoles.some((role) => allowedRoles.includes(role));

    if (!hasAllowedRole) {
      return router.parseUrl('/unauthorized');
    }

    return true;
  };
}
