// frontend/inchain-angular/src/app/layouts/app-layout.component.ts
import { Component, inject, OnInit, signal } from '@angular/core';
import { Router, RouterModule } from '@angular/router';
import { AuthService } from '@/features/auth/auth.service';
import { SidebarComponent } from '@/layouts/sidebar.component';
import { getNavigationItems } from '@/layouts/navigation.config';

@Component({
  selector: 'app-layout',
  imports: [RouterModule, SidebarComponent],
  templateUrl: './app-layout.component.html',
})
export class AppLayoutComponent implements OnInit {
  private readonly authService = inject(AuthService);
  private readonly router = inject(Router);

  protected readonly sidebarCollapsed = signal(false);
  protected readonly showLogoutConfirm = signal(false);
  protected readonly navigationItems = getNavigationItems(this.authService.roles());
  protected readonly userName = this.authService.currentUser()?.fullName || 'User';
  protected readonly currentPath = signal(this.router.url);

  ngOnInit(): void {
    this.router.events.subscribe(() => {
      this.currentPath.set(this.router.url);
    });
  }

  protected promptLogout(): void {
    this.showLogoutConfirm.set(true);
  }

  protected cancelLogout(): void {
    this.showLogoutConfirm.set(false);
  }

  protected confirmLogout(): void {
    this.authService.logout();
  }

  protected toggleSidebar(): void {
    this.sidebarCollapsed.update((v) => !v);
  }
}

<div class="flex h-dvh overflow-hidden">
  <app-sidebar
    [navigationItems]="navigationItems"
    [activePath]="currentPath()"
    [userName]="userName"
    [collapsed]="sidebarCollapsed()"
    (logOut)="promptLogout()"
    (toggleCollapse)="toggleSidebar()"
  />
  <main class="flex-1 overflow-y-auto bg-background">
    <div class="mx-auto max-w-6xl px-6 py-8">
      <router-outlet />
    </div>
  </main>

  <!-- Logout confirmation -->
  @if (showLogoutConfirm()) {
    <div class="fixed inset-0 z-50 bg-black/50" (click)="cancelLogout()"></div>
    <div class="fixed inset-0 z-50 flex items-center justify-center p-4">
      <div class="w-full max-w-sm rounded-2xl border border-border bg-background p-6 shadow-xl">
        <p class="text-sm font-medium">Sign out?</p>
        <p class="mt-1 text-sm text-muted-foreground">You will be returned to the login screen.</p>
        <div class="mt-4 flex items-center justify-end gap-2">
          <button
            type="button"
            class="rounded-lg border border-border px-3 py-1.5 text-sm font-medium transition-colors hover:bg-muted"
            (click)="cancelLogout()"
          >Cancel</button>
          <button
            type="button"
            class="rounded-lg bg-primary px-3 py-1.5 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90"
            (click)="confirmLogout()"
          >Sign out</button>
        </div>
      </div>
    </div>
  }
</div>

// frontend/inchain-react/src/layouts/AppLayout.tsx
import { NavLink, Outlet } from "react-router";
import { useAuth } from "../features/auth/useAuth";
import { getNavigationItems } from "./navigation";

function AppLayout() {
  const { logout, roles, user } = useAuth();
  const navigationItems = getNavigationItems(roles);

  return (
    <div className="min-h-screen bg-slate-50 text-slate-950">
      <aside className="fixed inset-y-0 left-0 flex w-64 flex-col border-r border-slate-200 bg-white">
        <div className="border-b border-slate-200 px-6 py-5">
          <p className="text-lg font-semibold">Inchain</p>
        </div>
        <nav className="flex flex-1 flex-col gap-1 px-3 py-4">
          {navigationItems.map((item) => (
            <NavLink
              key={item.to}
              to={item.to}
              className={({ isActive }) =>
                [
                  "rounded-md px-3 py-2 text-sm font-medium transition-colors",
                  isActive
                    ? "bg-slate-950 text-white"
                    : "text-slate-700 hover:bg-slate-100 hover:text-slate-950",
                ].join(" ")
              }
            >
              {item.label}
            </NavLink>
          ))}
        </nav>
      </aside>
      <div className="min-h-screen pl-64">
        <header className="sticky top-0 z-10 flex h-16 items-center justify-between border-b border-slate-200 bg-white px-6">
          <div>
            <p className="text-sm font-medium">{user?.fullName ?? user?.email ?? "User"}</p>
            <p className="text-xs text-slate-500">{roles.join(", ") || "No role assigned"}</p>
          </div>
          <button
            type="button"
            onClick={() => void logout()}
            className="rounded-md border border-slate-300 px-3 py-2 text-sm font-medium text-slate-700 hover:bg-slate-100"
          >
            Log out
          </button>
        </header>
        <main className="p-6">
          <Outlet />
        </main>
      </div>
    </div>
  );
}

export default AppLayout;
